networks:
  default:
    name: docker-default-network
    external: true

services:
  opa:
   build: ./opa # Dockerfile local dir
   hostname: opa
   mem_limit: 30m
   mem_reservation: 20m

  cors:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8181:80"
